site_name: Birdhouse
nav:
  - Overview: index.md
  - FAIR Climate Services: fair_cs.md
  - How To Do's: howtodos.md
  - Tutorials: tutorials.md
  - Demonstrators: demonstrators.md
  - List of Applications: list_apps.md
  - Release Notes: release_notes.md
  - References: bibliography.md 
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.ico