site_name: Birdhouse
nav:
  - Overview: index.md
  - FAIR Climate Services: fair_cs.md
  - Applications List: apps.md
  - Application development: guide_applications.md
  - Portals for Climate Services: guide_GUI-phoenix.md
  - Deploy a Climate Service: guide_deploy.md
  - Services and Initiatives: initiatives.md
  - Tutorials: tutorials.md
  - Release Notes: release_notes.md
  - Further reading: publications.md 
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.ico
plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
      csl_file: "nature.csl"
markdown_extensions:
  - footnotes