site_name: Birdhouse
nav:
  - Overview: index.md
  - FAIR Climate Services: fair_cs.md
  - Application development: guide_applications.md
  - Climate Services Ecosystem: guide_deploy.md
  - Portals for Climate Services: guide_GUI-phoenix.md
  - Commands for Climate Services: guide_commands.md
  - Tutorials: tutorials.md
  - Demonstrators: demonstrators.md
  - Contribution: contribution.md
  - Release Notes: release_notes.md
  - References: bibliography.md 
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.ico